package com.youtube.database.classes;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig youtubeDaoConfig;

    private final NoteDao noteDao;
    private final YouTubeModelDao youTubeModelDao ;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        youtubeDaoConfig = daoConfigMap.get(YouTubeModelDao.class).clone();
        youtubeDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        youTubeModelDao = new YouTubeModelDao(youtubeDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(YouTubeModel.class, youTubeModelDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        youtubeDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public YouTubeModelDao getYouTubeModelDao() {
        return youTubeModelDao;
    }

}
